palavra = input('Digite algo: ')
print(f'O tipo primitivo é {type(palavra)}')
print(f'Só tem espaços? {palavra.isspace()}')
print(f'É um número? {palavra.isnumeric()}')
print(f'É alfabético? {palavra.isalpha()}')
print(f'É alfanumérico? {palavra.isalnum()}')
print(f'Está em minúscula? {palavra.islower()}')
print(f'Está em maiúscula? {palavra.isupper()}')
print(f'Está capitalizada? {palavra.istitle()}')
